# Generated by Django 3.1.5 on 2021-01-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/imag1.jpg', upload_to='images/'),
        ),
    ]
